### ISSUE TITLE
use a SDT prefix on AWS_ROLE_ARN

### ISSUE THREAD

**Issue by kapilt** [capitalone/stack-deployment-tool#6]
else its ns pollution that's tool specific

**Comment by jdamick** [comment]
i can see the argument, are you concerned the sdk will be looking for AWS_ROLE_ARN at some point and that it would have a different meaning?  It seems clearer to the user to just use AWS as the prefix since they are already setting other AWS_* environment variables to be used by the sdk using SDT_ might be more confusing that it's worth to not pollute.. that was my thought when naming it.

**Comment by jdamick** [comment]
i'm closing..
